# Generated by Django 4.2.14 on 2024-08-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_deck_cardlog_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
