# Generated by Django 4.2.14 on 2024-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_deck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='question_text',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
