# Generated by Django 4.2.14 on 2024-08-18 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='answer_text',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardlog',
            name='experience',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cardlog',
            name='question_text',
            field=models.CharField(default=' ', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='last_remembered',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 10, 49, 14, 496506, tzinfo=datetime.timezone.utc), verbose_name='last remembered'),
        ),
    ]
