# Generated by Django 4.2.14 on 2024-08-18 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardlog_answer_text_cardlog_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_remembered',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 18, 12, 29, 18, 623772, tzinfo=datetime.timezone.utc), verbose_name='last remembered'),
        ),
        migrations.AlterField(
            model_name='cardlog',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
