# Generated by Django 4.2.14 on 2025-04-06 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_last_remembered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardlog',
            name='time_to_learn',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 3, 24, 21, 801820, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_remembered',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 3, 24, 21, 800849, tzinfo=datetime.timezone.utc), verbose_name='last remembered'),
        ),
    ]
