# Generated by Django 4.2.14 on 2025-04-06 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_cardlog_time_to_learn_alter_card_last_remembered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardlog',
            name='time_to_learn',
        ),
        migrations.AddField(
            model_name='card',
            name='time_to_learn',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 3, 39, 55, 445467, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_remembered',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 3, 39, 55, 445467, tzinfo=datetime.timezone.utc), verbose_name='last remembered'),
        ),
    ]
